[project]
name = "nostrfun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bech32>=1.2.0",
    "nostr-sdk>=0.42.1",
]
